name: agrimatco
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.5.0
  easy_localization: ^2.3.3
  get: ^3.26.0
  google_fonts: ^1.1.2
  font_awesome_flutter: ^8.11.0
  carousel_slider: ^3.0.0
  smooth_page_indicator: ^0.2.1
  shimmer: ^1.1.2
  photo_view: ^0.10.3
  smooth_star_rating: ^1.1.1
  line_icons: ^1.3.2
  line_awesome_flutter: ^1.0.1
  flutter_swiper: ^1.1.6
  url_launcher: ^6.0.2
  share: ^2.0.0
  flutter_secure_storage: ^4.0.0
  flutter_staggered_animations: ^0.1.3
  fl_chart: ^0.20.1
  start_chart: ^0.2.0
  pie_chart: ^5.0.0
  google_maps_flutter: ^2.0.1
  percent_indicator: ^2.1.9+1
  dio_http_cache: ^0.2.11
  dio: ^3.0.10
  provider: ^5.0.0
  splashscreen: ^1.3.5
  http: ^0.12.0+4
  after_layout: ^1.0.7+2
  toast: ^0.1.5
  shared_preferences: ^0.5.12+4
  flutter_spinkit: ^5.0.0
  pull_to_refresh: ^1.6.4
  geolocator: any
  avatar_glow:
  onesignal_flutter: ^2.6.3
  progress_dialog: ^1.2.4
  loading_animations: ^2.1.0
  flutter_boom_menu: ^1.0.2
  giffy_dialog: ^1.8.0
  slimy_card: ^1.0.4
  badges: ^1.2.0
#  flutter_simple_calculator: 2.0.0-nullsafety.1
  intl_phone_field: ^1.4.4
  weather_widget: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: ^0.0.1
#  flutter_launcher_icons: ^0.9.0

flutter_launcher_name:
  name: "Agrimatco"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/languages/ar-IQ.json
    - assets/languages/en-US.json
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: PFDinTextArabic
      fonts:
        - asset: assets/fonts/PFDinTextArabic-Regular.ttf
        - asset: assets/fonts/PFDinTextArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/PFDinTextArabic-Bold.ttf
          weight: 700
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
